### PR TITLE
A number of improvements and features

### PR DESCRIPTION
**Pull request by kravietz**
* Database.design_upload() to compile CouchApp style directories into a design document
* the design functions can be now minified using YUICompressor
* __str__ methods added to Database and Server classes
* new Database.config() method (find last_seq or number of documents there)

### CODE REVIEW

**Comment by histrio** [comment]
Hello Paweł! Thanks for contributing but I don't want accept new features, yet. Also, I do not think that the project needs a new requirements (yuicompressor). 
Can you build a new pull request with some minor changes?

**Comment by histrio** [comment]
Besides, there are some merge conflicts exists. Can you update your fork?

**Comment by histrio** [comment]
@kravietz any feedback?

**Comment by kravietz** [comment]
Hi Rinat, I made these changes as part of ongoing project but haven't really had time to make any changes since then.

**Comment by kravietz** [comment]
I have resolved the conflicts but as for the general patch perhaps it's best if you just cherry-pick whatever you like from my commits. I need all features I added for my projects so I'll still need to maintain my fork anyway.

**Comment by histrio** [comment]
@kravietz ok. I'll try to pick your commits partially. 
I have one technical question: in server's `changes_feed` method, `chunk_size` is important to be `1`?

**Comment by histrio** [comment]
Thank you very much for your commits. I'll try to merge/reimplement this features later.

**Comment by kravietz** [comment]
Hm, not sure about this chunk_size - I must have taken this from requests API I believe and I don't remember any particular reason why it's 1.

**Pull request closed without merging**
