### PR TITLE
Implement Pagination with Start Key for CouchDB Views

### PR DESCRIPTION
**Pull request by Phoenix009**
[Reference](https://docs.couchdb.org/en/stable/ddocs/views/pagination.html#paging-alternate-method)

This pull request adds a feature to paginate CouchDB views using the `startkey` parameter along with `limit`. 
This approach improves the efficiency of pagination in CouchDB, enabling clients to retrieve specific segments of a view based on a designated `startkey` without the performance drawbacks of the `skip` parameter.

### CODE REVIEW

**Comment by Phoenix009** [comment]
@histrio Can you please give some details as to why the CI stage failed. 
I can take a look and try to resolve the issue

**Comment by histrio** [comment]
@Phoenix009 sorry for a late reply
for some reason test for python3.10 and couchdb 1.7 is hanging for 6 hours
I will take a look little bit later

**Comment by Phoenix009** [comment]
@histrio, I just wanted to check if there are any updates for this PR.
Let me know if there is any assistance required

**Comment by histrio** [comment]
@Phoenix009 Hi!
I did the same test locally and there were no issues. Meanwhile, GitHub actions still freeze on 3.9/3.10 + 1.7.

**Pull request merged**
